.github/workflows/gh-pages.yaml, site/astro.config.mjs, site/src/components/Header.astro, site/src/layouts/Layout.astro, site/src/lib/nav-links.ts, site/src/pages/collections/index.astro, site/src/pages/index.astro
This uses Astro's GitHub action and workflow template to deploy the build to GitHub pages.
- Updated Astro config to include `site` and `base` to support the GitHub pages destination
- Updated hrefs to reference `import.meta.env.BASE_URL` where absolute URLs are necessary (e.g. within `Layout.astro` and isolated components)
- Updated hrefs to use relative URLs when possible (e.g. within specific `pages`)
- Set `trailingSlash: "always"` and updated all links to include trailing slashes, for predictable relative hrefs (AFAIK github pages already auto-suffixes with a trailing slash, but I'm being safe for any potential future switch)
Example deployment from testing on my fork: https://kfranqueiro.github.io/fixable/
The built version can be previewed locally using `npm run build` followed by …
=> Add workflow to deploy to GitHub pages

site/src/components/CollectionCard.astro, site/src/components/LaxImage.astro, site/src/pages/collections/[tag].astro
This brings CollectionCard back to roughly its earlier behavior, but without forcibly distorting images nor forcing specification of `alt` (since I'm guessing we'll want to intentionally omit it for a failure at some point).
I had previously removed usage of the `Image` component because it forces specification of alt in the input and width/height in its output. The problem with removing that is it balloons image asset sizes, because the source assets are huge. This PR introduces a `LaxImage` component that reproduces most of `Image`'s behavior, without those limitations.
I also added a missing style to CollectionCard to fix the side-by-side layout for tall images (e.g. the 2nd item on the toys page).
=> Add LaxImage component and use for CollectionCard

site/src/components/Footer.astro, site/src/components/meta/MetaFailureSection.astro, site/src/layouts/Layout.astro, site/src/layouts/MetaLayout.astro, site/src/lib/meta.ts, site/src/pages/index.astro, site/src/pages/museum/index.astro, site/src/pages/museum/volunteer/index.astro
This adds a new top-level index page with information about breakages implemented in the Museum site.
It also replaces the expandable section at the bottom of individual pages with a link (for now, possibly a dialog w/ iframe later) pointing to the specific section in the top-level page discussing the page in question.
The top-level page sets up sections with specifically-named IDs (with the help of a reusable component, `MetaFailureSection`) to make this Just Work from individual pages based on their path. If a path does not match to an ID as expected, an error message will be shown in local dev only (not in builds).
Link in museum page footers:
Example when following a link back to a matching section:
Example in dev when the specified hash is not found:
=> Add meta homepage; replace expandable footer with link

site/src/components/Header.astro, site/src/components/UserControls.astro
This is a small follow-up to the persistence added in #9.
When signed in successfully, the sign in button in the header will be replaced with a sign out button via client-side scripting.
Upon clicking sign-out, the logged-in state will be cleared and the current page will be re-navigated (intentionally not using `reload()` since that has potential to repeat signing in).
(If we want a dedicated sign out page that makes the user wait a few seconds, that can be arranged.)
=> Implement sign in/out button swap based on stored state

site/src/lib/client/store.ts, site/src/pages/museum/gift-shop/index.astro
This creates some minimally-styled markup on the gift shop page so I could build and test cart functionality.
This will presumably be spread across multiple pages once we have more fleshed-out data and designs for it.
Note: This all uses vanilla JS; I carried forward the assumption that we want to avoid libraries. I presume that the cart is likely to be the most client-side-scripting-heavy feature of the site, and this still isn't a terrible amount of code as-is, though it might be more ergonomic with e.g. a Preact island. We can make a call on that, or at least rearrange cart functions into a dedicated TS file if that ends up making sense, once we understand how the fully-structured gift shop will work.
=> Implement prototype gift shop page with functional cart

site/src/components/Fixable.astro, site/src/components/Timeout.astro, site/src/components/cart/CartInventory.astro, site/src/components/cart/CartStatus.astro, site/src/components/meta/MetaFailureSection.astro, site/src/lib/client/cart.ts, site/src/lib/client/form.ts, site/src/lib/client/store.ts, site/src/pages/index.astro, site/src/pages/museum/gift-shop/checkout/confirmation.astro, site/src/pages/museum/gift-shop/checkout/index.astro, site/src/pages/museum/gift-shop/checkout/payment.astro, site/src/pages/museum/gift-shop/checkout/review.astro, site/src/pages/museum/gift-shop/checkout/shipping.astro, site/src/pages/museum/gift-shop/index.astro, site/src/pages/museum/login/index.astro, site/src/pages/museum/volunteer/index.astro
This adds functionality for a multi-step checkout flow:
- Intentionally shows no indications of the full process or which step number the user is on
- All fields are intentionally unlabeled
- There is intentionally only a generic error above all fields; each invalid field is only marked using border color
- There is intentionally no up-front indication of required fields
Styles are currently minimal, pending input from designers.
An initial pass at updates to the meta homepage is included.
Additional changes:
- Refactored existing cart logic (from #14) into components/functions for reuse between shop and checkout
- Refactored timeout logic (originally from #10) into component for reuse between volunteer form and checkout steps
- Added `onStoreChange` API for DOM updates in reaction to …
=> Add checkout flow

README.md, site/package.json, site/tsconfig.json
Changes:
- Expands node docs, attempts to further emphasize `site` directory, and moves node above docker as it is likely easier for most users
- Adds `check` script
- Updates tsconfig so `check` won't flag built content under `dist`
=> Update Node docs, add check script, avoid checking dist

site/src/pages/index.astro, site/src/pages/museum/gift-shop/checkout/payment.astro, site/src/pages/museum/login/index.astro
This disallows paste on the login page to fail accessible authentication criteria, and fixes the no-paste behavior on the payments page to only affect inputs within the main form (i.e. not the search input).
=> Disallow paste on login page

site/src/components/UserControls.astro, site/src/lib/client/form.ts, site/src/lib/client/store.ts, site/src/pages/index.astro, site/src/pages/museum/gift-shop/checkout/payment.astro, site/src/pages/museum/gift-shop/checkout/shipping.astro, site/src/pages/museum/login/index.astro, site/src/pages/museum/register.astro
This adds a Register page (accessed from and complementing the existing Sign In page) which includes a client-side-generated CAPTCHA with no alternative, failing SC 1.1.1.
Changes aside from the new page:
- Updated `validateInputs` to always rely on a Zod schema
- Added persistence of registration information, which is now used to validate the sign in form instead of static/hard-coded credentials
- Updated `isLoggedIn` to `loggedInAt`, to add future possibility of time-based session expiration
=> Add Register page with CAPTCHA

site/src/assets/styles/form-elements.css, site/src/components/Fixable.astro, site/src/components/FormLayout.astro, site/src/lib/client/store.ts, site/src/pages/museum/gift-shop/checkout/payment.astro, site/src/pages/museum/gift-shop/checkout/shipping.astro, site/src/pages/museum/login/index.astro, site/src/pages/museum/register.astro, site/src/pages/museum/volunteer/index.astro
- Add validation to more fields e.g. email, non-empty password + confirmation
- Add name field to shipping form (for added repetition with payment form)
- Add per-field error revalidation to shipping form and run it initially in broken version for worst possible UX
- Remove per-field revalidation from login form since it doesn't have nearly as noticeable effects there
- Login: move error notification above fields and add spacing to make zoomed scroll a more plausible issue
- Registration: add error notification above fields, similar to login but also omit ARIA role in broken version
- Remove subheadings from broken shipping/payment checkout steps to more blatantly fail criteria
- Add `FormLayout` component to centralize repeated form styles (they're still minimal but they're already used …
=> Add more form-related failures

site/src/components/cart/CartStatus.astro
This fixes an error that was easy to overlook in dev mode but causes the Continue button not to render in checkout when the site is built for production.
=> Fix checkout-specific CartStatus error

site/package-lock.json, site/package.json, site/src/components/Header.astro, site/src/components/Search.astro, site/src/pages/index.astro, site/src/pages/museum/api/search.ts, site/src/pages/museum/map.astro, site/src/pages/museum/search.astro
This implements client-side search behavior and hooks it up to the search input in a way that should fail multiple SCs (documented in the top-level index).
- Populates a static endpoint with search result data which is fetched then filtered client-side (currently only includes top-level pages; could add collection data at a later point when we have more of it)
- Hooks up search behavior using a debounced input event handler, which then replaces the content of the page causing a change in context (and neglects to update page title)
- Removes surrounding form and search button (still present in fixed version)
- Creates a search page so that directly accessing the URLs created by the client-side logic will also work (which also ensures the corrected form works)
- Fixed a title typo I noticed …
=> Implement inaccessible search behavior

site/src/components/Search.astro, site/src/lib/client/fetch.ts
This works around an issue with #18 that I wasn't able to see until it hit GitHub Pages.
When working locally, both in dev and preview, the code in that PR worked fine. On GitHub Pages, however, the request for `/fixable/museum/api/search/` fails. Without the trailing slash, it succeeds, but that in turn fails in local environments. Relocating `api/search.ts` to `api/search/index.ts` has no effect on the situation.
This PR works around this by performing a 2nd fallback request if necessary in production mode, leading with the URL that is expected to work on GitHub Pages. When running in dev mode, the URL with trailing slash is immediately requested, since that is known to work in local development. The only case that will result in a 404 + fallback request is local `npm run preview`. …
=> Work around webhost path handling discrepancies; fix TS error

site/src/assets/styles/content-layout.css, site/src/assets/styles/utilities.css, site/src/components/CollectionCard.astro, site/src/components/CoverImage.astro, site/src/components/Footer.astro, site/src/components/Navigation.astro, site/src/layouts/Layout.astro, site/src/lib/nav-links.ts, site/src/pages/museum/index.astro
This includes some cleanup and preparatory work on the way to laying out collection and gift shop listing pages.
- Remove `wrapper` element from layout because it was proving to be actively harmful and not useful
- IIUC, subgrids only work if every intermediate level forwards it, which would need to include `main`, which would not be useful in the majority of pages
- Currently we were only using this for the equivalent of auto left/right margins + max-width on `main` (which is what I've changed the `main` element to now do instead)
- The grid was effectively requiring the page to always be extremely wide, causing horizontal scrolling on _all_ pages at anything below nearly-full-screen desktop. While we might want this to break in some places, we probably don't want it broken _everywhere_ …
=> Rework layout, incl. repurposed grid, and mobile breakpoints

site/src/assets/styles/utilities.css, site/src/components/Footer.astro
This fixes a regression I didn't realize I caused while I was iterating on responsive styles, noticeable if you go to gift shop checkout with 0 items in cart (the continue button shouldn't be visible).
I had originally gone in the direction of adding responsive classes to "undo" display: none at breakpoints which is why I removed the `!important` and added the `block` class, but I ultimately ended up doing the opposite direction with the use of media range queries, so I can reinstate these. I still find it unfortunate to need to use `!important`, but it's somewhat necessary given unpredictable order of component styles.
=> Fix hidden styles

site/src/layouts/Layout.astro, site/src/pages/index.astro, site/src/pages/museum/tour.astro
- Filled out tour page with role=alert element that updates every 15 seconds
- Added support for overriding nav bar links within the main Layout; set to skip "Take a Tour" on the tour page itself
- Take an upcoming tour link 404s (will see overly-vague error page once #31 is merged)
=> Populate tour page with overly-frequent alerts and inconsistent nav

site/src/components/Modal.astro, site/src/content/config.ts, site/src/content/exhibit-categories/dishes.md, site/src/content/exhibit-categories/home.md, site/src/pages/index.astro, site/src/pages/museum/collections/[category]/index.astro, site/src/pages/museum/collections/index.astro
- Add support for marking a collection as "dangerous":
- Hides it from the overall Collection list page
- Shows a warning modal on that collection's own list page; no flashing occurs until a choice is made in the modal
- The failure choices add a "lightning" effect to the exhibits on the collection's list page (AAA uses white, A uses red)
- The "no failures" choice applies a gradual fade instead
- Add `dangerous: true` to Home collection, removing it from the overall Collections list page
- Add `top*` properties to Home collection and remove from Dishes collection, adding it to the Home page, which is the only place it will be linked from
Modal component updates:
- Adds `mode` optional property, to allow forcing fixed mode even when the site is in broken mode
- Removes `class` property, …
=> Mark Home collection as dangerous; add "lightning" effect to its list

site/src/assets/styles/content-layout.css, site/src/components/Carousel.astro, site/src/pages/index.astro, site/src/pages/museum/blog/[category]/[post].astro, site/src/pages/museum/index.astro
This adds a carousel to the top of the homepage, with the following properties in broken mode:
- Does not properly mark hidden items as inert, so they occupy tab stops even when not visible
- Fixed mode adds `inert` to hidden items
- Includes motion/scale animations on the full entries and individual text items without honoring prefers-reduced-motion
- Fixed mode only uses a fade animation on full entries and does not animate individual text items
- Lacks next/previous and pause/play controls
- This is not yet addressed for fixed mode
=> Add Carousel component to museum home page

site/src/content/exhibits/home/narrow-room.md, site/src/content/exhibits/home/porch-chair.md, site/src/content/exhibits/home/wide-bedroom.md, site/src/pages/index.astro, site/src/pages/museum/collections/[category]/[exhibit].astro
This is follow-up to #30, adding parallax effect to the background on individual exhibit pages in the home collection.
- Adds alternate rendering to the exhibit page for "dangerous" collections (only the Home collection is marked dangerous; this is the same flag used for the flashing effects in #30)
- Adds more content to the Home entries to ensure a noticeable range of parallax motion while also trying to avoid being extremely fast
- The warning modal on the collection page already mentions these pages having parallax
=> Add background parallax to home category exhibits

site/src/lib/image.ts, site/src/pages/index.astro, site/src/pages/museum/collections/index.astro
This updates the page at /fixable/museum/collections, which we hadn't really paid much attention to.
- Adds masonry layout with images for each collection (using the first entry found for each category)
- Each link's text only visibly appears on hover (not focus)
- Explicit tabindex attributes are used on the masonry layout links
- This makes them occur before even header content in tab order
- The links within "See More" are not included in this explicit ordering
- The order is hard-coded against the widest layout, meaning it is further incorrect even within the collection links on narrower viewports
- The "See More" box includes links that are "moved" out of the header nav
Other code changes:
- Created a helper function under lib/image for instances where we want a downsampled image but …
=> Add masonry to collections list page

site/src/components/Favorite.astro, site/src/lib/client/store.ts, site/src/pages/index.astro, site/src/pages/museum/collections/[category]/[exhibit].astro
This adds an icon overlaying the top-right corner of each exhibit's image on individual exhibit pages. Clicking the icon toggles persistent state that is maintained individually for each exhibit.
- The broken version uses a div with no programmatic indication of it being interactive and no tab stop
- The fixed version uses a button with role="checkbox" and aria-checked, though I imagine there could be several ways to go about this and maybe something else is preferable?
Things I intentionally did not do in this PR:
- I did not make this reveal only on hover, because that might make the other issues too easy to overlook
- I did not add this to grid cells in each collection listing, because I already have thoughts about something we can do on top of that (namely making each entire cell a …
=> Add Favorite toggle to individual exhibit pages

site/package-lock.json, site/package.json
This upgrades Astro and should resolve a npm audit warning we've been getting lately.
I tested the build and went through a bunch of pages to check that nothing unexpectedly broke.
=> Upgrade Astro to 4.15.1

site/src/components/Search.astro
1. Add some padding to the search box so It matches the button.
2. Fix an issue where search results were presented in a `ul`  element and had commas in-between each`li` element.
3. Corrected the syntax for the nested button element in the CSS, but I’m still not sure it does anything.
=> Fix two search issues

site/src/pages/museum/about.astro
1. Give it the incorrect role of `grid`
2. Add `role=columnheader` attributes to heading cells in “desktop” breakpoint
3. Change layout of table in “responsive” breakpoint, but keep the `columnheader` roles, which results in incorrect announcements by screen readers
4. The times are inconsistent in the responsive version, with every day being 9-5 instead of Saturday and Sunday having extended hours.
=> Worsen the opening hours table

site/src/layouts/Layout.astro, site/src/pages/index.astro, site/src/pages/museum/blog/index.astro
This implements an idea Rachael suggested recently, which is to intentionally break the skip link on one page.
This PR adds a prop to the layout which can do this on demand, and applies it to the blog listing page (not individual posts).
=> Intentionally break skip link on blog listing page

README.md, site/package-lock.json, site/package.json
This configures scripts using `cross-env` for easier invocations across platforms (especially Windows), and documents "fixed" mode in the readme. I had initially held back documenting that because it's so incomplete, but I've been mentioning it in a couple of PRs so it kind of needs to be documented.
I also removed the intro paragraph under development environment because it should not take "a day or two" to set up a dev environment for this project; that sounds excessively daunting...
=> Add cross-env for fixed-mode scripts; update readme

site/src/assets/styles/utilities.css, site/src/components/Search.astro, site/src/layouts/BaseLayout.astro
Fixes #47.
The cause of the issue was the `popstate` event handler hooked up for the broken version's search box. This handler was also firing on hash changes, and hitting the code path intended for leaving the search page via browser history, which has the effect of refreshing the page.
We thought the issue was only happening on Chromium derivatives, but it was actually happening even in Firefox. The difference is Firefox was somehow resilient enough to still follow the hash change, so the problem was less noticeable.
The fix is adding conditions in the event handler; while debugging this I also realized we could simplify the CSS used to make the skip link visible on focus, so that's also included in this PR.
=> Fix skip link behavior and simplify its CSS

site/src/components/ConditionalParent.astro, site/src/components/Fixable.astro, site/src/components/types.ts, site/src/pages/index.astro, site/src/pages/museum/collections/[category]/index.astro
The main goal of this PR is to cause failures due to overly-verbose links that bury the important part at the end, by wrapping images (with alt text) within links on one collection's list of exhibits, thus achieving the effect of a common "card" anti-pattern.
This PR also includes some refactoring of typings, since I added a `ConditionalParent` component to make conditional wrappers easier, which relies on similar typings to what `Fixable` already used. (The code removed from `Fixable` now exists in `components/types.ts`.)
=> Include exhibit images within links on music collection page

site/src/pages/museum/map.astro
I spent time today installing adb and setting up wireless debugging for mobile Firefox and got to the bottom of this issue.
Turns out that for some reason, `movementX` and `movementY` are always zero during `pointermove`. Neither Android Chrome nor iOS Safari seem to have this problem.
Fortunately, the code already has sufficient variables sitting around from the pinch-zoom case to fix this, and doing so also makes "delayed" pinches more consistent. Previously, if you pressed one finger and moved it around significantly before pressing a second finger to pinch, it would "jump" because the primary X/Y were not being updated in the single-touch case.
I also added one other commit here for something else I noticed in the map page - I had somehow reversed the wording in the instructions about …
=> Map: fix panning on Android Firefox

site/src/components/Header.astro, site/src/components/Search.astro, site/src/layouts/Layout.astro, site/src/pages/museum/index.astro
This adds plumbing to the Search, Header, and Layout components to be able to override whether the broken or fixed version of the Search component is used, defaulting to the overall mode the site is being run/built in and only being overridable to fixed (i.e. you can't break it in fixed mode).
I also fixed the submit button in the fixed version, which I realized I hadn't included any sort of text label in.
This PR does not include any update to the top-level index page, since the search failures are already documented in the Home & Search section.
=> Only break search on museum home page

site/src/components/Footer.astro, site/src/components/meta/MetaFailureSection.astro, site/src/layouts/Layout.astro, site/src/lib/meta.ts
- Removes the "what's wrong" link to accommodate initial use cases for the site
- Documents function this was using to produce slugs for URI fragments
- Updates MetaFailureSection to use the same function (I tested the links still worked before removing them)
- Only reduce the attribution paragraph font size in gift shop pages
- Adds `mode` parameter to Footer component, defaulting to whatever mode the site is running/built in
- Forces `mode` to `fixed` for default museum layout
- (Added after rebase over #52) Explicitly set footer background to gray-900 (darker than black variable) to make gold stand out more
=> Footer: Remove "what's wrong" link; only include small font in shop

site/src/pages/index.astro, site/src/pages/museum/collections/[category]/index.astro
This is effectively a variation on #40 for a different collection. This wraps each entry's image in a separate link, and sets the image's alt text to the same content as the text label, resulting in duplicate links for each entry.
I made an attempt at updating the top-level index with things I think this would fail, but I'm a bit up in the air on whether there's a better fit, especially for WCAG 2.
=> Duplicate entry links in sports collection page

site/src/components/Carousel.astro, site/src/components/Footer.astro, site/src/components/Navigation.astro, site/src/layouts/Layout.astro, site/src/layouts/ShopLayout.astro, site/src/lib/nav-links.ts, site/src/pages/index.astro, site/src/pages/museum/blog/[category]/[post].astro, site/src/pages/museum/blog/index.astro, site/src/pages/museum/collections/index.astro, site/src/pages/museum/tour.astro
This reorganizes the nav to include 2 submenus:
- Collections (lists some specific collections + an "all collections" link that goes to where the Collections nav item went before)
- Visit (includes Museum Map and Take a Tour
On most pages, submenus use a button for their top-level entry which includes `aria-controls` pointing to the submenu list, and `aria-expanded` which the CSS uses to control visibility. Submenus close upon losing focus or upon escape keypress.
The following pages are intentionally broken (when not run in fixed mode):
- On gift shop pages: submenus trigger specifically on hover and are completely inaccessible via keyboard
- On blog pages: submenus trigger specifically on focus, and focus needs to be moved in order to close them
- `nav-links.ts`: Nav list is …
=> Implement fly-out nav menu with 3 variants

.github/workflows/pr-build.yaml
This runs `npm run check` on PRs, to ensure that we don't accidentally merge something with errors that can be caught at build time.
(This does not run the full build, since typically the `check` step is what will fail, and the full build takes close to a full minute on github, primarily due to optimizing images.)
- [Example failed run](https://github.com/kfranqueiro/fixable/actions/runs/10818896170/job/30015538034?pr=1)
- [Example successful run](https://github.com/kfranqueiro/fixable/actions/runs/10818908992/job/30015581323?pr=1)
=> Add workflow to run check on PRs

site/src/components/CookieBanner.astro, site/src/components/Footer.astro, site/src/layouts/Layout.astro, site/src/lib/client/store.ts, site/src/pages/index.astro, site/src/pages/museum/index.astro
This fails both Focus not Obscured criteria by placing a cookie banner at the bottom left of the home page in a way that should be guaranteed to cover one or more of the links in the footer. The banner is intentionally placed after the footer in the document order to attempt to highlight the issue.
The banner dismisses upon clicking either button, and will not be shown again (unless you clear localStorage).
(Regardless of what the banner says, the code in this repo never stores cookies.)
Note: This PR removes the link around "Unsplash" in the footer to avoid needing to work around it in the fixed version.
=> Add cookie banner at bottom of home page

site/src/components/Navigation.astro, site/src/pages/index.astro
This adds styles that only apply to nav submenu links on pages with `failureMode: "focus"` (currently blog listing + post pages), to make their focus indicator only a bottom border below each link, which is both ambiguous due to equal distance between items, and low-contrast against the background when the bottom item is focused.
Note: this only updates the WCAG 2 failures under the Blog section, because the WCAG 3 section only exists in another PR. I will have to update that in whichever of the two PRs merge last.
=> Fail Focus Appearance on nav submenu links on Blog pages

site/src/components/Footer.astro, site/src/layouts/ShopLayout.astro, site/src/pages/index.astro
- Adds "Established in 2024" right below the logo in the footer, except for Gift Shop pages which show the year in Roman numerals
- Adds a help contact number at the end of the footer, except for Gift Shop pages which instead have this number at the end of the main content before the footer starts
=> Add (inconsistent) help and year to footer

site/src/assets/styles/content-layout.css, site/src/components/Carousel.astro, site/src/components/CookieBanner.astro, site/src/components/FormLayout.astro, site/src/components/cart/CartInventory.astro, site/src/pages/museum/blog/[category]/[post].astro, site/src/pages/museum/index.astro
The global `outset` styles (used on the home page and blog post pages) caused a problem on user agents with discrete scrollbars (i.e. scrollbars that occupy width/height as opposed to being overlaid) due to using `calc(100% - 100vw)`. This PR uses alternative means to accomplish the full-width backgrounds used on these pages. (The diff for `pages/museum/index.astro` will be easier to read with `?w=1` to ignore whitespace.)
While I was working on this, I noticed an instance of a nested selector not working in Safari 16 (due to not starting with a symbol), and I knew there were likely a few other instances of this across the codebase, so I resolved all that I found (most visibly affecting login/shop/volunteer forms and the cart inventory page in checkout).
=> Fix horizontal scrollbars; improve compatibility of nested selectors

site/src/assets/styles/form-elements.css, site/src/components/FormLayout.astro, site/src/pages/index.astro, site/src/pages/museum/register.astro
This updates the CAPTCHA input field on the register page to only be indicated by a low-contrast underline, with the focus state additionally being low-contrast against the base style, and the text cursor/caret being completely invisible.
I reduced specificity in some common CSS to help support this.
=> Add contrast-related failures to the CAPTCHA input

site/src/assets/styles/form-elements.css, site/src/components/FormLayout.astro, site/src/pages/index.astro, site/src/pages/museum/register.astro
This is a repeat of #64 which got lost when I repaired main related to a mis-merge of #55.
=>  Add contrast-related failures to the CAPTCHA input

site/src/components/Video.astro, site/src/pages/museum/index.astro
This fixes 3 things:
- Replaces hard-coded `/fixable/` with `import.meta.env.BASE_URL` (which I should have thought of when reviewing #70); this has no effect on this repository but will fix the videos on the W3C version
- Restores original placement of width/height styles in Video component (this was my mistake during cleanup, which caused an issue on the Tour page)
- Insets the heading added to the home page (a change related to another PR that merged between when the Video PR opened and was merged)
=> Don't hard-code base URL in Video component

site/src/pages/index.astro, site/src/pages/museum/early-home-computers-event.astro
These issues were flagged by @fstrr.
Meta page changes:
- Adds a link to the museum home page in the top section (which is always displayed)
- Removes a redundant paragraph from the top section that wouldn't make sense without the failures section, working whatever unique information it had into the top paragraph inside the failures section
Early home computers event page changes:
- Split styles into 2 sections: one with `is:global is:inline` for only the styles that need to appear last to override global CSS from Layout, and the other with neither flag for styles that can be scoped and bundled/optimized
- Relatedly, this allows removing the `page` class from `header` since its styles are now automatically scoped
- Fixed formatting; shortened top/right/bottom/left 0 to inset 0
=> Address meta page and early home computers page issues

site/src/pages/museum/gift-shop/checkout/payment.astro, site/src/pages/museum/gift-shop/checkout/shipping.astro, site/src/pages/museum/volunteer/index.astro
This extends the timeouts on the volunteer form and the checkout forms (shipping / payment) to 60 seconds.
=> Extend form timeouts from 30s to 60s

site/src/pages/index.astro
- Expands the docs at the top of the top-level index page regarding site behavior, to be more noticeable and to explain locally-functional registration/sign-in behavior
- Replaces the word "scrim" with clearer wording to avoid confusion
=> Improve top-level index docs

site/package-lock.json
This resolves the current dependabot alerts:
- https://github.com/accessiblecommunity/fixable/security/dependabot/6
- https://github.com/accessiblecommunity/fixable/security/dependabot/8
- https://github.com/accessiblecommunity/fixable/security/dependabot/9
Ran a test build and tested a few pages across the site. This strictly involves a patch version update to Vite and minor version update to Rollup, so there shouldn't be breakage risk. These tools are also only used at dev/build time.
=> Update Vite to 5.4.7 and Rollup to 4.22.4 to resolve vulnerabilities

site/src/components/Toast.astro, site/src/lib/client/toast.ts
This addresses a critical functionality bug, and another potential unintended usability snag in the Toast component, plus includes some fixes/improvements for the fixed version of the component.
- Conditionalizes awaiting `toastTransitionPromise` to avoid incurring a race condition when consecutively hiding then performing an action that shows a new toast; previously, this would close the first toast but then break the component's state, preventing any future toasts from displaying. (Thanks @julierawe for spotting this!)
- Switches the icons from filled to outlined versions, to attempt to make it more clear that they're not interactable
- Removes `form method="dialog"` from fixed version of component so that more of the existing code paths (and transitions) work identically between both …
=> Toast: Fix action to not break future toasts; improve fixed version

site/package-lock.json, site/package.json, site/src/components/Carousel.astro, site/src/components/CoverImage.astro, site/src/content.config.ts, site/src/env.d.ts, site/src/lib/markdown.ts, site/src/pages/museum/blog/[category]/[post].astro, site/src/pages/museum/blog/index.astro, site/src/pages/museum/collections/[category]/[exhibit].astro, site/src/pages/museum/collections/[category]/index.astro, site/src/pages/museum/collections/index.astro, site/src/pages/museum/gift-shop/[category]/[product].astro, site/src/pages/museum/gift-shop/[category]/index.astro, site/src/pages/museum/gift-shop/index.astro, site/src/pages/museum/index.astro, site/tsconfig.json
I saw a few dependabot alerts and figured now would also be a good time to upgrade Astro from 4 to 5, to keep us up to date with the current state of their docs.
Most of the changes made in this PR can be explained by points in https://docs.astro.build/en/guides/upgrade-to/v5/, especially the section under Legacy for content collections. There are a couple of other typing-related changes that were necessary as well.
I performed a new build, confirmed no TypeScript errors, and tested across all types of pages on the site to confirm identical behavior.
=> Upgrade to Astro 5

site/package-lock.json, site/package.json
Verified that nothing changes in build output other than `generator` meta tag and hashes in asset files.
=> Upgrade Astro to 5.2 and update vulnerable dependencies

package-lock.json, site/src/pages/index.astro, site/src/pages/museum/volunteer/index.astro
Adds a "did you mean [this email provider]" prompt in the volunteer sign up form. Updates list of issues.
=> Do you mean email
